steps:
  - label: ":python: test core"
    command: "./run_unit_tests.sh tests.core:CoreTest"
    plugins:
      docker#v1.4.0:
        image: "python:3.6.5"
  - label: ":docker: build image"
    command: ".buildkite/pipeline-docker-build.sh dev"
    agents:
      queue: "deploy"
    plugins:
      ecr#v1.1.2:
        login: true,
        no-include-email: true,
        account_ids: ${AWS_ACCOUNT_IDS}
